"""add niveles to progreso_leccion

Revision ID: 4858c23833e7
Revises: f8af64dab6af
Create Date: 2026-06-26 02:01:18.654457
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4858c23833e7'
down_revision: Union[str, None] = 'f8af64dab6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progreso_leccion', sa.Column('nivel_actual', sa.Integer(), server_default='1', nullable=False))
    op.add_column('progreso_leccion', sa.Column('nivel_completado', sa.Integer(), server_default='0', nullable=False))
    op.add_column('progreso_leccion', sa.Column('intentos_nivel', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progreso_leccion', 'intentos_nivel')
    op.drop_column('progreso_leccion', 'nivel_completado')
    op.drop_column('progreso_leccion', 'nivel_actual')
    # ### end Alembic commands ###
