"""tablas iniciales Sprint 1

Revision ID: 72b392e3ec6a
Revises: 
Create Date: 2026-06-17 23:20:11.867708
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '72b392e3ec6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('grado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('estudiante', 'docente', 'administrador', name='rol_usuario'), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grado_id'], ['grado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=True)
    op.create_table('libro_texto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=False),
    sa.Column('archivo_pdf_path', sa.String(length=500), nullable=False),
    sa.Column('estado_indexacion', sa.Enum('pendiente', 'procesando', 'completado', 'error', name='estado_indexacion'), nullable=False),
    sa.Column('confianza_ocr_promedio', sa.Float(), nullable=True),
    sa.Column('total_paginas', sa.Integer(), nullable=True),
    sa.Column('paginas_procesadas', sa.Integer(), nullable=True),
    sa.Column('error_detalle', sa.Text(), nullable=True),
    sa.Column('subido_por', sa.Integer(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.ForeignKeyConstraint(['grado_id'], ['grado.id'], ),
    sa.ForeignKeyConstraint(['subido_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fragmento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('contenido_texto', sa.Text(), nullable=False),
    sa.Column('numero_pagina', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=300), nullable=True),
    sa.Column('chunk_id_vectordb', sa.String(length=100), nullable=False),
    sa.Column('confianza_ocr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['libro_id'], ['libro_texto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id_vectordb')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fragmento')
    op.drop_table('libro_texto')
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('grado')
    op.drop_table('asignatura')
    # ### end Alembic commands ###
