"""Sprint 2: chat, actividades, perfil

Revision ID: dc87596ca1e1
Revises: 72b392e3ec6a
Create Date: 2026-06-18 22:54:01.883857
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dc87596ca1e1'
down_revision: Union[str, None] = '72b392e3ec6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('opcion_multiple', 'verdadero_falso', 'completar', 'ordenar', 'respuesta_corta', name='tipo_actividad'), nullable=False),
    sa.Column('tema', sa.Text(), nullable=True),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('respuesta_correcta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.ForeignKeyConstraint(['grado_id'], ['grado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_ultimo_mensaje', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversacion_estudiante_id'), 'conversacion', ['estudiante_id'], unique=False)
    op.create_table('perfil_comprension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('asignatura_id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=300), nullable=False),
    sa.Column('puntaje_promedio', sa.Float(), nullable=False),
    sa.Column('total_actividades', sa.Integer(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asignatura_id'], ['asignatura.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_comprension_estudiante_id'), 'perfil_comprension', ['estudiante_id'], unique=False)
    op.create_table('resultado_actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('respuesta_estudiante', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('puntaje', sa.Float(), nullable=False),
    sa.Column('retroalimentacion', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('usuario', 'asistente', name='rol_mensaje'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('referencias', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensaje_conversacion_id'), 'mensaje', ['conversacion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensaje_conversacion_id'), table_name='mensaje')
    op.drop_table('mensaje')
    op.drop_table('resultado_actividad')
    op.drop_index(op.f('ix_perfil_comprension_estudiante_id'), table_name='perfil_comprension')
    op.drop_table('perfil_comprension')
    op.drop_index(op.f('ix_conversacion_estudiante_id'), table_name='conversacion')
    op.drop_table('conversacion')
    op.drop_table('actividad')
    # ### end Alembic commands ###
