"""add leccion and progreso_leccion tables

Revision ID: e64612b9c574
Revises: dc87596ca1e1
Create Date: 2026-06-21 01:26:14.403015
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e64612b9c574'
down_revision: Union[str, None] = 'dc87596ca1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('tema_clave', sa.String(length=200), nullable=False),
    sa.Column('paginas', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['libro_id'], ['libro_texto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progreso_leccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('leccion_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('bloqueada', 'disponible', 'en_progreso', 'completada', name='estado_leccion'), nullable=False),
    sa.Column('puntaje_promedio', sa.Float(), nullable=False),
    sa.Column('actividades_completadas', sa.Integer(), nullable=False),
    sa.Column('actividades_requeridas', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_completada', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['leccion_id'], ['leccion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudiante_id', 'leccion_id', name='uq_progreso_estudiante_leccion')
    )
    op.create_index(op.f('ix_progreso_leccion_estudiante_id'), 'progreso_leccion', ['estudiante_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progreso_leccion_estudiante_id'), table_name='progreso_leccion')
    op.drop_table('progreso_leccion')
    op.drop_table('leccion')
    # ### end Alembic commands ###
