"""add gamificacion fields to usuario

Revision ID: f8af64dab6af
Revises: e64612b9c574
Create Date: 2026-06-21 02:24:31.032467
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8af64dab6af'
down_revision: Union[str, None] = 'e64612b9c574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('racha_actual', sa.Integer(), server_default='0', nullable=False))
    op.add_column('usuario', sa.Column('mejor_racha', sa.Integer(), server_default='0', nullable=False))
    op.add_column('usuario', sa.Column('ultima_actividad', sa.Date(), nullable=True))
    op.add_column('usuario', sa.Column('puntos_totales', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'puntos_totales')
    op.drop_column('usuario', 'ultima_actividad')
    op.drop_column('usuario', 'mejor_racha')
    op.drop_column('usuario', 'racha_actual')
    # ### end Alembic commands ###
